language: python
python: "2.7"
script: python -m unittest discover -s tests -p '*.py'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ef7eac7a5044c1233d9b
    on_success: always
    on_failure: always
    on_start: never
